// This file is auto-generated by @hey-api/openapi-ts

export const AllStatsSchema = {
  properties: {
    currStreak: {
      type: 'integer',
      title: 'Currstreak',
    },
    maxStreak: {
      type: 'integer',
      title: 'Maxstreak',
    },
    stats: {
      items: {
        $ref: '#/components/schemas/DayStat',
      },
      type: 'array',
      title: 'Stats',
    },
  },
  type: 'object',
  required: ['currStreak', 'maxStreak', 'stats'],
  title: 'AllStats',
} as const;

export const Body_add_file_storage__postSchema = {
  properties: {
    file: {
      type: 'string',
      format: 'binary',
      title: 'File',
    },
  },
  type: 'object',
  required: ['file'],
  title: 'Body_add_file_storage__post',
} as const;

export const Body_create_card_cards__postSchema = {
  properties: {
    card: {
      $ref: '#/components/schemas/CardCreate',
    },
    collections: {
      items: {
        type: 'integer',
      },
      type: 'array',
      maxItems: 100,
      minItems: 1,
      title: 'Collections',
    },
  },
  type: 'object',
  required: ['card', 'collections'],
  title: 'Body_create_card_cards__post',
} as const;

export const Body_update_card_cards__card_id__putSchema = {
  properties: {
    new_card: {
      $ref: '#/components/schemas/CardCreate',
    },
    collections: {
      items: {
        type: 'integer',
      },
      type: 'array',
      maxItems: 100,
      minItems: 1,
      title: 'Collections',
    },
  },
  type: 'object',
  required: ['new_card', 'collections'],
  title: 'Body_update_card_cards__card_id__put',
} as const;

export const CardSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    isPublic: {
      type: 'boolean',
      title: 'Ispublic',
    },
    frontSide: {
      type: 'string',
      minLength: 1,
      title: 'Frontside',
    },
    backSide: {
      type: 'string',
      minLength: 1,
      title: 'Backside',
    },
    ownerId: {
      type: 'integer',
      title: 'Ownerid',
    },
  },
  type: 'object',
  required: ['id', 'isPublic', 'frontSide', 'backSide', 'ownerId'],
  title: 'Card',
} as const;

export const CardCreateSchema = {
  properties: {
    frontSide: {
      type: 'string',
      minLength: 1,
      title: 'Frontside',
    },
    backSide: {
      type: 'string',
      minLength: 1,
      title: 'Backside',
    },
  },
  type: 'object',
  required: ['frontSide', 'backSide'],
  title: 'CardCreate',
} as const;

export const CollectionSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    isPublic: {
      type: 'boolean',
      title: 'Ispublic',
    },
    title: {
      type: 'string',
      maxLength: 100,
      minLength: 1,
      title: 'Title',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    ownerId: {
      type: 'integer',
      title: 'Ownerid',
    },
  },
  type: 'object',
  required: ['id', 'isPublic', 'title', 'ownerId'],
  title: 'Collection',
} as const;

export const CollectionCreateSchema = {
  properties: {
    title: {
      type: 'string',
      maxLength: 100,
      minLength: 1,
      title: 'Title',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
  },
  type: 'object',
  required: ['title'],
  title: 'CollectionCreate',
} as const;

export const CollectionShortSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    isPublic: {
      type: 'boolean',
      title: 'Ispublic',
    },
    ownerId: {
      type: 'integer',
      title: 'Ownerid',
    },
    title: {
      type: 'string',
      maxLength: 100,
      minLength: 1,
      title: 'Title',
    },
  },
  type: 'object',
  required: ['id', 'isPublic', 'ownerId', 'title'],
  title: 'CollectionShort',
} as const;

export const CollectionStatsSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    avgCurrentRetrievability: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Avgcurrentretrievability',
    },
    avgStability: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Avgstability',
    },
    avgDifficulty: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Avgdifficulty',
    },
    avgAfterYearRetrievability: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Avgafteryearretrievability',
    },
  },
  type: 'object',
  required: [
    'id',
    'avgCurrentRetrievability',
    'avgStability',
    'avgDifficulty',
    'avgAfterYearRetrievability',
  ],
  title: 'CollectionStats',
} as const;

export const DayStatSchema = {
  properties: {
    trainDate: {
      type: 'string',
      format: 'date',
      title: 'Traindate',
    },
    cnt: {
      type: 'integer',
      title: 'Cnt',
    },
    avgMark: {
      type: 'number',
      title: 'Avgmark',
    },
    totalDuration: {
      type: 'integer',
      title: 'Totalduration',
    },
    logs: {
      items: {
        $ref: '#/components/schemas/TrainLog',
      },
      type: 'array',
      title: 'Logs',
    },
  },
  type: 'object',
  required: ['trainDate', 'cnt', 'avgMark', 'totalDuration', 'logs'],
  title: 'DayStat',
} as const;

export const FileMetaSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    isPublic: {
      type: 'boolean',
      title: 'Ispublic',
    },
    ownerId: {
      type: 'integer',
      title: 'Ownerid',
    },
    filename: {
      type: 'string',
      title: 'Filename',
    },
    type: {
      type: 'string',
      enum: ['image', 'video', 'audio'],
      title: 'Type',
    },
    ext: {
      type: 'string',
      enum: [
        'bmp',
        'gif',
        'jpg',
        'jpeg',
        'png',
        'svg',
        'tif',
        'tiff',
        'webp',
        'avi',
        'm4v',
        'mkv',
        'mov',
        'mpg',
        'mp4',
        'ogv',
        'webm',
        'wmv',
        'aac',
        'flac',
        'm4a',
        'mp3',
        'mpeg',
        'oga',
        'ogg',
        'wav',
      ],
      title: 'Ext',
    },
    size: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Size',
    },
  },
  type: 'object',
  required: ['id', 'isPublic', 'ownerId', 'filename', 'type', 'ext', 'size'],
  title: 'FileMeta',
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  title: 'HTTPValidationError',
} as const;

export const TrainCardExtSchema = {
  properties: {
    userId: {
      type: 'integer',
      title: 'Userid',
    },
    cardId: {
      type: 'integer',
      title: 'Cardid',
    },
    state: {
      type: 'integer',
      title: 'State',
    },
    step: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Step',
    },
    stability: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Stability',
    },
    difficulty: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Difficulty',
    },
    due: {
      type: 'string',
      format: 'date-time',
      title: 'Due',
    },
    lastReview: {
      anyOf: [
        {
          type: 'string',
          format: 'date-time',
        },
        {
          type: 'null',
        },
      ],
      title: 'Lastreview',
    },
    currentRetrievability: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Currentretrievability',
    },
    afterYearRetrievability: {
      anyOf: [
        {
          type: 'number',
        },
        {
          type: 'null',
        },
      ],
      title: 'Afteryearretrievability',
    },
  },
  type: 'object',
  required: [
    'userId',
    'cardId',
    'state',
    'step',
    'stability',
    'difficulty',
    'due',
    'lastReview',
    'currentRetrievability',
    'afterYearRetrievability',
  ],
  title: 'TrainCardExt',
} as const;

export const TrainDueSchema = {
  properties: {
    type: {
      type: 'string',
      const: 'due',
      title: 'Type',
    },
    due: {
      type: 'string',
      format: 'date-time',
      title: 'Due',
    },
  },
  type: 'object',
  required: ['type', 'due'],
  title: 'TrainDue',
} as const;

export const TrainLogSchema = {
  properties: {
    userId: {
      type: 'integer',
      title: 'Userid',
    },
    cardId: {
      type: 'integer',
      title: 'Cardid',
    },
    rating: {
      type: 'integer',
      title: 'Rating',
    },
    reviewDatetime: {
      type: 'string',
      format: 'date-time',
      title: 'Reviewdatetime',
    },
    reviewDuration: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Reviewduration',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
  },
  type: 'object',
  required: [
    'userId',
    'cardId',
    'rating',
    'reviewDatetime',
    'reviewDuration',
    'id',
  ],
  title: 'TrainLog',
} as const;

export const TrainMarkAnswerSchema = {
  properties: {
    mark: {
      type: 'integer',
      maximum: 4,
      minimum: 1,
      title: 'Mark',
    },
    durationMs: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Durationms',
    },
  },
  type: 'object',
  required: ['mark', 'durationMs'],
  title: 'TrainMarkAnswer',
} as const;

export const TrainNowSchema = {
  properties: {
    type: {
      type: 'string',
      const: 'now',
      title: 'Type',
    },
  },
  type: 'object',
  required: ['type'],
  title: 'TrainNow',
} as const;

export const TrainPlanSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    cardsToTrain: {
      items: {
        type: 'integer',
      },
      type: 'array',
      title: 'Cardstotrain',
    },
  },
  type: 'object',
  required: ['id', 'cardsToTrain'],
  title: 'TrainPlan',
} as const;

export const TrainWhenSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    when: {
      oneOf: [
        {
          $ref: '#/components/schemas/TrainNow',
        },
        {
          $ref: '#/components/schemas/TrainDue',
        },
      ],
      title: 'When',
      discriminator: {
        propertyName: 'type',
        mapping: {
          due: '#/components/schemas/TrainDue',
          now: '#/components/schemas/TrainNow',
        },
      },
    },
  },
  type: 'object',
  required: ['id', 'when'],
  title: 'TrainWhen',
} as const;

export const UserSchema = {
  properties: {
    nickname: {
      type: 'string',
      maxLength: 35,
      minLength: 1,
      title: 'Nickname',
    },
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['nickname', 'email', 'id'],
  title: 'User',
} as const;

export const UserAuthSchema = {
  properties: {
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
    password: {
      type: 'string',
      maxLength: 40,
      minLength: 8,
      title: 'Password',
    },
  },
  type: 'object',
  required: ['email', 'password'],
  title: 'UserAuth',
} as const;

export const UserBaseSchema = {
  properties: {
    nickname: {
      type: 'string',
      maxLength: 35,
      minLength: 1,
      title: 'Nickname',
    },
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
  },
  type: 'object',
  required: ['nickname', 'email'],
  title: 'UserBase',
} as const;

export const UserCreateSchema = {
  properties: {
    nickname: {
      type: 'string',
      maxLength: 35,
      minLength: 1,
      title: 'Nickname',
    },
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
    password: {
      type: 'string',
      maxLength: 40,
      minLength: 8,
      title: 'Password',
    },
  },
  type: 'object',
  required: ['nickname', 'email', 'password'],
  title: 'UserCreate',
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
      title: 'Location',
    },
    msg: {
      type: 'string',
      title: 'Message',
    },
    type: {
      type: 'string',
      title: 'Error Type',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
} as const;
