// This file is auto-generated by @hey-api/openapi-ts

export const Body_add_file_storage__postSchema = {
  properties: {
    file: {
      type: 'string',
      format: 'binary',
      title: 'File',
    },
  },
  type: 'object',
  required: ['file'],
  title: 'Body_add_file_storage__post',
} as const;

export const Body_create_card_cards__postSchema = {
  properties: {
    card: {
      $ref: '#/components/schemas/CardCreate',
    },
    collections: {
      items: {
        type: 'integer',
      },
      type: 'array',
      maxItems: 100,
      minItems: 1,
      title: 'Collections',
    },
  },
  type: 'object',
  required: ['card', 'collections'],
  title: 'Body_create_card_cards__post',
} as const;

export const Body_update_card_cards__card_id__putSchema = {
  properties: {
    new_card: {
      $ref: '#/components/schemas/CardCreate',
    },
    collections: {
      items: {
        type: 'integer',
      },
      type: 'array',
      maxItems: 100,
      minItems: 1,
      title: 'Collections',
    },
  },
  type: 'object',
  required: ['new_card', 'collections'],
  title: 'Body_update_card_cards__card_id__put',
} as const;

export const CardSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    isPublic: {
      type: 'boolean',
      title: 'Ispublic',
    },
    frontSide: {
      type: 'string',
      minLength: 1,
      title: 'Frontside',
    },
    backSide: {
      type: 'string',
      minLength: 1,
      title: 'Backside',
    },
    ownerId: {
      type: 'integer',
      title: 'Ownerid',
    },
  },
  type: 'object',
  required: ['id', 'isPublic', 'frontSide', 'backSide', 'ownerId'],
  title: 'Card',
} as const;

export const CardCreateSchema = {
  properties: {
    frontSide: {
      type: 'string',
      minLength: 1,
      title: 'Frontside',
    },
    backSide: {
      type: 'string',
      minLength: 1,
      title: 'Backside',
    },
  },
  type: 'object',
  required: ['frontSide', 'backSide'],
  title: 'CardCreate',
} as const;

export const CollectionSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    isPublic: {
      type: 'boolean',
      title: 'Ispublic',
    },
    title: {
      type: 'string',
      maxLength: 100,
      minLength: 1,
      title: 'Title',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
    ownerId: {
      type: 'integer',
      title: 'Ownerid',
    },
  },
  type: 'object',
  required: ['id', 'isPublic', 'title', 'ownerId'],
  title: 'Collection',
} as const;

export const CollectionCreateSchema = {
  properties: {
    title: {
      type: 'string',
      maxLength: 100,
      minLength: 1,
      title: 'Title',
    },
    description: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'null',
        },
      ],
      title: 'Description',
    },
  },
  type: 'object',
  required: ['title'],
  title: 'CollectionCreate',
} as const;

export const CollectionShortSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    isPublic: {
      type: 'boolean',
      title: 'Ispublic',
    },
    ownerId: {
      type: 'integer',
      title: 'Ownerid',
    },
    title: {
      type: 'string',
      maxLength: 100,
      minLength: 1,
      title: 'Title',
    },
  },
  type: 'object',
  required: ['id', 'isPublic', 'ownerId', 'title'],
  title: 'CollectionShort',
} as const;

export const FileMetaSchema = {
  properties: {
    id: {
      type: 'integer',
      title: 'Id',
    },
    isPublic: {
      type: 'boolean',
      title: 'Ispublic',
    },
    ownerId: {
      type: 'integer',
      title: 'Ownerid',
    },
    filename: {
      type: 'string',
      title: 'Filename',
    },
    type: {
      type: 'string',
      enum: ['image', 'video', 'audio'],
      title: 'Type',
    },
    ext: {
      type: 'string',
      enum: [
        'bmp',
        'gif',
        'jpg',
        'jpeg',
        'png',
        'svg',
        'tif',
        'tiff',
        'webp',
        'avi',
        'm4v',
        'mkv',
        'mov',
        'mpg',
        'mp4',
        'ogv',
        'webm',
        'wmv',
        'aac',
        'flac',
        'm4a',
        'mp3',
        'mpeg',
        'oga',
        'ogg',
        'wav',
      ],
      title: 'Ext',
    },
    size: {
      anyOf: [
        {
          type: 'integer',
        },
        {
          type: 'null',
        },
      ],
      title: 'Size',
    },
  },
  type: 'object',
  required: ['id', 'isPublic', 'ownerId', 'filename', 'type', 'ext', 'size'],
  title: 'FileMeta',
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: '#/components/schemas/ValidationError',
      },
      type: 'array',
      title: 'Detail',
    },
  },
  type: 'object',
  title: 'HTTPValidationError',
} as const;

export const TrainRecordSchema = {
  properties: {
    mark: {
      type: 'integer',
      maximum: 5,
      minimum: 1,
      title: 'Mark',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
    cardId: {
      type: 'integer',
      title: 'Cardid',
    },
    userId: {
      type: 'integer',
      title: 'Userid',
    },
    repeatDate: {
      type: 'string',
      format: 'date-time',
      title: 'Repeatdate',
    },
    nextRepeatDate: {
      type: 'string',
      format: 'date-time',
      title: 'Nextrepeatdate',
    },
    progress: {
      type: 'number',
      maximum: 1,
      minimum: 0,
      title: 'Progress',
    },
  },
  type: 'object',
  required: [
    'mark',
    'id',
    'cardId',
    'userId',
    'repeatDate',
    'nextRepeatDate',
    'progress',
  ],
  title: 'TrainRecord',
} as const;

export const TrainRecordCreateSchema = {
  properties: {
    mark: {
      type: 'integer',
      maximum: 5,
      minimum: 1,
      title: 'Mark',
    },
  },
  type: 'object',
  required: ['mark'],
  title: 'TrainRecordCreate',
} as const;

export const UserSchema = {
  properties: {
    nickname: {
      type: 'string',
      maxLength: 35,
      minLength: 1,
      title: 'Nickname',
    },
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
    id: {
      type: 'integer',
      title: 'Id',
    },
  },
  type: 'object',
  required: ['nickname', 'email', 'id'],
  title: 'User',
} as const;

export const UserAuthSchema = {
  properties: {
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
    password: {
      type: 'string',
      maxLength: 40,
      minLength: 8,
      title: 'Password',
    },
  },
  type: 'object',
  required: ['email', 'password'],
  title: 'UserAuth',
} as const;

export const UserBaseSchema = {
  properties: {
    nickname: {
      type: 'string',
      maxLength: 35,
      minLength: 1,
      title: 'Nickname',
    },
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
  },
  type: 'object',
  required: ['nickname', 'email'],
  title: 'UserBase',
} as const;

export const UserCreateSchema = {
  properties: {
    nickname: {
      type: 'string',
      maxLength: 35,
      minLength: 1,
      title: 'Nickname',
    },
    email: {
      type: 'string',
      format: 'email',
      title: 'Email',
    },
    password: {
      type: 'string',
      maxLength: 40,
      minLength: 8,
      title: 'Password',
    },
  },
  type: 'object',
  required: ['nickname', 'email', 'password'],
  title: 'UserCreate',
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string',
          },
          {
            type: 'integer',
          },
        ],
      },
      type: 'array',
      title: 'Location',
    },
    msg: {
      type: 'string',
      title: 'Message',
    },
    type: {
      type: 'string',
      title: 'Error Type',
    },
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError',
} as const;
