// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
  formDataBodySerializer,
} from '@hey-api/client-fetch';
import type {
  ReadCardCardsCardIdGetData,
  ReadCardCardsCardIdGetError,
  ReadCardCardsCardIdGetResponse,
  UpdateCardCardsCardIdPutData,
  UpdateCardCardsCardIdPutError,
  UpdateCardCardsCardIdPutResponse,
  DeleteCardCardsCardIdDeleteData,
  DeleteCardCardsCardIdDeleteError,
  DeleteCardCardsCardIdDeleteResponse,
  ReadCardCollectionsCardsCardIdCollectionsGetData,
  ReadCardCollectionsCardsCardIdCollectionsGetError,
  ReadCardCollectionsCardsCardIdCollectionsGetResponse,
  ReadCardFilesCardsCardIdFilesGetData,
  ReadCardFilesCardsCardIdFilesGetError,
  ReadCardFilesCardsCardIdFilesGetResponse,
  CreateCardCardsPostData,
  CreateCardCardsPostError,
  CreateCardCardsPostResponse,
  ReadCollectionCollectionsCollectionIdGetData,
  ReadCollectionCollectionsCollectionIdGetError,
  ReadCollectionCollectionsCollectionIdGetResponse,
  UpdateCollectionCollectionsCollectionIdPutData,
  UpdateCollectionCollectionsCollectionIdPutError,
  UpdateCollectionCollectionsCollectionIdPutResponse,
  DeleteCollectionCollectionsCollectionIdDeleteData,
  DeleteCollectionCollectionsCollectionIdDeleteError,
  DeleteCollectionCollectionsCollectionIdDeleteResponse,
  ReadCollectionsCollectionsGetData,
  ReadCollectionsCollectionsGetError,
  ReadCollectionsCollectionsGetResponse,
  CreateCollectionCollectionsPostData,
  CreateCollectionCollectionsPostError,
  CreateCollectionCollectionsPostResponse,
  ReadCollectionCardsCollectionsCollectionIdCardsGetData,
  ReadCollectionCardsCollectionsCollectionIdCardsGetError,
  ReadCollectionCardsCollectionsCollectionIdCardsGetResponse,
  SubscribeCollectionsCollectionIdSubscribePostData,
  SubscribeCollectionsCollectionIdSubscribePostError,
  SubscribeCollectionsCollectionIdSubscribePostResponse,
  UnsubscribeCollectionsCollectionIdUnsubscribeDeleteData,
  UnsubscribeCollectionsCollectionIdUnsubscribeDeleteError,
  UnsubscribeCollectionsCollectionIdUnsubscribeDeleteResponse,
  UpdateCollectionPublicityCollectionsCollectionIdPublicityPutData,
  UpdateCollectionPublicityCollectionsCollectionIdPublicityPutError,
  UpdateCollectionPublicityCollectionsCollectionIdPublicityPutResponse,
  AddFileStoragePostData,
  AddFileStoragePostError,
  AddFileStoragePostResponse,
  GetFileMetaStorageFileIdMetaGetData,
  GetFileMetaStorageFileIdMetaGetError,
  GetFileMetaStorageFileIdMetaGetResponse,
  GetFileCardsStorageFileIdCardsGetData,
  GetFileCardsStorageFileIdCardsGetError,
  GetFileCardsStorageFileIdCardsGetResponse,
  GetFileStorageFileIdGetData,
  GetFileStorageFileIdGetError,
  GetFileStorageFileIdGetResponse,
  DeleteFileStorageFileIdDeleteData,
  DeleteFileStorageFileIdDeleteError,
  DeleteFileStorageFileIdDeleteResponse,
  TrainCardTrainCardIdPostData,
  TrainCardTrainCardIdPostError,
  TrainCardTrainCardIdPostResponse,
  GetCollectionTrainWhenTrainCollectionCollectionIdWhenGetData,
  GetCollectionTrainWhenTrainCollectionCollectionIdWhenGetError,
  GetCollectionTrainWhenTrainCollectionCollectionIdWhenGetResponse,
  GetCollectionTrainCardsTrainCollectionCollectionIdCardsGetData,
  GetCollectionTrainCardsTrainCollectionCollectionIdCardsGetError,
  GetCollectionTrainCardsTrainCollectionCollectionIdCardsGetResponse,
  GetUserStatsTrainStatsAllGetError,
  GetUserStatsTrainStatsAllGetResponse,
  GetCardStatsTrainStatsCardCardIdGetData,
  GetCardStatsTrainStatsCardCardIdGetError,
  GetCardStatsTrainStatsCardCardIdGetResponse,
  GetCollectionStatsTrainStatsCollectionCollectionIdGetData,
  GetCollectionStatsTrainStatsCollectionCollectionIdGetError,
  GetCollectionStatsTrainStatsCollectionCollectionIdGetResponse,
  ReadUserUserProfileGetError,
  ReadUserUserProfileGetResponse,
  ReadUserSubscriptionsUserSubscriptionsGetData,
  ReadUserSubscriptionsUserSubscriptionsGetError,
  ReadUserSubscriptionsUserSubscriptionsGetResponse,
  ReadUserCollectionsUserCollectionsGetData,
  ReadUserCollectionsUserCollectionsGetError,
  ReadUserCollectionsUserCollectionsGetResponse,
  ReadUserCardsUserCardsGetData,
  ReadUserCardsUserCardsGetError,
  ReadUserCardsUserCardsGetResponse,
  ReadUserFilesUserFilesGetData,
  ReadUserFilesUserFilesGetError,
  ReadUserFilesUserFilesGetResponse,
  CreateUserUserRegisterPostData,
  CreateUserUserRegisterPostError,
  CreateUserUserRegisterPostResponse,
  UpdateUserUserEditProfilePutData,
  UpdateUserUserEditProfilePutError,
  UpdateUserUserEditProfilePutResponse,
  DeleteUserUserDeleteProfileDeleteError,
  DeleteUserUserDeleteProfileDeleteResponse,
  AuthenticateUserUserLoginPostData,
  AuthenticateUserUserLoginPostError,
  AuthenticateUserUserLoginPostResponse,
  LogoutUserUserLogoutPostError,
  LogoutUserUserLogoutPostResponse,
} from './types.gen';

export const client = createClient(createConfig());

/**
 * Read Card
 */
export const readCardCardsCardIdGet = <ThrowOnError extends boolean = false>(
  options: Options<ReadCardCardsCardIdGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ReadCardCardsCardIdGetResponse,
    ReadCardCardsCardIdGetError,
    ThrowOnError
  >({
    ...options,
    url: '/cards/{card_id}',
  });
};

/**
 * Update Card
 */
export const updateCardCardsCardIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateCardCardsCardIdPutData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    UpdateCardCardsCardIdPutResponse,
    UpdateCardCardsCardIdPutError,
    ThrowOnError
  >({
    ...options,
    url: '/cards/{card_id}',
  });
};

/**
 * Delete Card
 */
export const deleteCardCardsCardIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteCardCardsCardIdDeleteData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteCardCardsCardIdDeleteResponse,
    DeleteCardCardsCardIdDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/cards/{card_id}',
  });
};

/**
 * Read Card Collections
 */
export const readCardCollectionsCardsCardIdCollectionsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadCardCollectionsCardsCardIdCollectionsGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    ReadCardCollectionsCardsCardIdCollectionsGetResponse,
    ReadCardCollectionsCardsCardIdCollectionsGetError,
    ThrowOnError
  >({
    ...options,
    url: '/cards/{card_id}/collections',
  });
};

/**
 * Read Card Files
 */
export const readCardFilesCardsCardIdFilesGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadCardFilesCardsCardIdFilesGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ReadCardFilesCardsCardIdFilesGetResponse,
    ReadCardFilesCardsCardIdFilesGetError,
    ThrowOnError
  >({
    ...options,
    url: '/cards/{card_id}/files',
  });
};

/**
 * Create Card
 */
export const createCardCardsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateCardCardsPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateCardCardsPostResponse,
    CreateCardCardsPostError,
    ThrowOnError
  >({
    ...options,
    url: '/cards/',
  });
};

/**
 * Read Collection
 */
export const readCollectionCollectionsCollectionIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ReadCollectionCollectionsCollectionIdGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ReadCollectionCollectionsCollectionIdGetResponse,
    ReadCollectionCollectionsCollectionIdGetError,
    ThrowOnError
  >({
    ...options,
    url: '/collections/{collection_id}',
  });
};

/**
 * Update Collection
 */
export const updateCollectionCollectionsCollectionIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateCollectionCollectionsCollectionIdPutData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    UpdateCollectionCollectionsCollectionIdPutResponse,
    UpdateCollectionCollectionsCollectionIdPutError,
    ThrowOnError
  >({
    ...options,
    url: '/collections/{collection_id}',
  });
};

/**
 * Delete Collection
 */
export const deleteCollectionCollectionsCollectionIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteCollectionCollectionsCollectionIdDeleteData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).delete<
    DeleteCollectionCollectionsCollectionIdDeleteResponse,
    DeleteCollectionCollectionsCollectionIdDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/collections/{collection_id}',
  });
};

/**
 * Read Collections
 * Returns collections' list without descriptions
 */
export const readCollectionsCollectionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ReadCollectionsCollectionsGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ReadCollectionsCollectionsGetResponse,
    ReadCollectionsCollectionsGetError,
    ThrowOnError
  >({
    ...options,
    url: '/collections/',
  });
};

/**
 * Create Collection
 */
export const createCollectionCollectionsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCollectionCollectionsPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateCollectionCollectionsPostResponse,
    CreateCollectionCollectionsPostError,
    ThrowOnError
  >({
    ...options,
    url: '/collections/',
  });
};

/**
 * Read Collection Cards
 */
export const readCollectionCardsCollectionsCollectionIdCardsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ReadCollectionCardsCollectionsCollectionIdCardsGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    ReadCollectionCardsCollectionsCollectionIdCardsGetResponse,
    ReadCollectionCardsCollectionsCollectionIdCardsGetError,
    ThrowOnError
  >({
    ...options,
    url: '/collections/{collection_id}/cards',
  });
};

/**
 * Subscribe
 */
export const subscribeCollectionsCollectionIdSubscribePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    SubscribeCollectionsCollectionIdSubscribePostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).post<
    SubscribeCollectionsCollectionIdSubscribePostResponse,
    SubscribeCollectionsCollectionIdSubscribePostError,
    ThrowOnError
  >({
    ...options,
    url: '/collections/{collection_id}/subscribe',
  });
};

/**
 * Unsubscribe
 */
export const unsubscribeCollectionsCollectionIdUnsubscribeDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UnsubscribeCollectionsCollectionIdUnsubscribeDeleteData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).delete<
    UnsubscribeCollectionsCollectionIdUnsubscribeDeleteResponse,
    UnsubscribeCollectionsCollectionIdUnsubscribeDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/collections/{collection_id}/unsubscribe',
  });
};

/**
 * Update Collection Publicity
 */
export const updateCollectionPublicityCollectionsCollectionIdPublicityPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateCollectionPublicityCollectionsCollectionIdPublicityPutData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).put<
    UpdateCollectionPublicityCollectionsCollectionIdPublicityPutResponse,
    UpdateCollectionPublicityCollectionsCollectionIdPublicityPutError,
    ThrowOnError
  >({
    ...options,
    url: '/collections/{collection_id}/publicity',
  });
};

/**
 * Add File
 */
export const addFileStoragePost = <ThrowOnError extends boolean = false>(
  options: Options<AddFileStoragePostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    AddFileStoragePostResponse,
    AddFileStoragePostError,
    ThrowOnError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      'Content-Type': null,
      ...options?.headers,
    },
    url: '/storage/',
  });
};

/**
 * Get File Meta
 */
export const getFileMetaStorageFileIdMetaGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetFileMetaStorageFileIdMetaGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetFileMetaStorageFileIdMetaGetResponse,
    GetFileMetaStorageFileIdMetaGetError,
    ThrowOnError
  >({
    ...options,
    url: '/storage/{file_id}/meta',
  });
};

/**
 * Get File Cards
 */
export const getFileCardsStorageFileIdCardsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetFileCardsStorageFileIdCardsGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetFileCardsStorageFileIdCardsGetResponse,
    GetFileCardsStorageFileIdCardsGetError,
    ThrowOnError
  >({
    ...options,
    url: '/storage/{file_id}/cards',
  });
};

/**
 * Get File
 */
export const getFileStorageFileIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetFileStorageFileIdGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetFileStorageFileIdGetResponse,
    GetFileStorageFileIdGetError,
    ThrowOnError
  >({
    ...options,
    url: '/storage/{file_id}',
  });
};

/**
 * Delete File
 */
export const deleteFileStorageFileIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteFileStorageFileIdDeleteData, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteFileStorageFileIdDeleteResponse,
    DeleteFileStorageFileIdDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/storage/{file_id}',
  });
};

/**
 * Train Card
 */
export const trainCardTrainCardIdPost = <ThrowOnError extends boolean = false>(
  options: Options<TrainCardTrainCardIdPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    TrainCardTrainCardIdPostResponse,
    TrainCardTrainCardIdPostError,
    ThrowOnError
  >({
    ...options,
    url: '/train/{card_id}',
  });
};

/**
 * Get Collection Train When
 */
export const getCollectionTrainWhenTrainCollectionCollectionIdWhenGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCollectionTrainWhenTrainCollectionCollectionIdWhenGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetCollectionTrainWhenTrainCollectionCollectionIdWhenGetResponse,
    GetCollectionTrainWhenTrainCollectionCollectionIdWhenGetError,
    ThrowOnError
  >({
    ...options,
    url: '/train/collection/{collection_id}/when',
  });
};

/**
 * Get Collection Train Cards
 */
export const getCollectionTrainCardsTrainCollectionCollectionIdCardsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCollectionTrainCardsTrainCollectionCollectionIdCardsGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetCollectionTrainCardsTrainCollectionCollectionIdCardsGetResponse,
    GetCollectionTrainCardsTrainCollectionCollectionIdCardsGetError,
    ThrowOnError
  >({
    ...options,
    url: '/train/collection/{collection_id}/cards',
  });
};

/**
 * Get User Stats
 */
export const getUserStatsTrainStatsAllGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetUserStatsTrainStatsAllGetResponse,
    GetUserStatsTrainStatsAllGetError,
    ThrowOnError
  >({
    ...options,
    url: '/train/stats/all',
  });
};

/**
 * Get Card Stats
 */
export const getCardStatsTrainStatsCardCardIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetCardStatsTrainStatsCardCardIdGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    GetCardStatsTrainStatsCardCardIdGetResponse,
    GetCardStatsTrainStatsCardCardIdGetError,
    ThrowOnError
  >({
    ...options,
    url: '/train/stats/card/{card_id}',
  });
};

/**
 * Get Collection Stats
 */
export const getCollectionStatsTrainStatsCollectionCollectionIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetCollectionStatsTrainStatsCollectionCollectionIdGetData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).get<
    GetCollectionStatsTrainStatsCollectionCollectionIdGetResponse,
    GetCollectionStatsTrainStatsCollectionCollectionIdGetError,
    ThrowOnError
  >({
    ...options,
    url: '/train/stats/collection/{collection_id}',
  });
};

/**
 * Read User
 */
export const readUserUserProfileGet = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ReadUserUserProfileGetResponse,
    ReadUserUserProfileGetError,
    ThrowOnError
  >({
    ...options,
    url: '/user/profile',
  });
};

/**
 * Read User Subscriptions
 */
export const readUserSubscriptionsUserSubscriptionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ReadUserSubscriptionsUserSubscriptionsGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ReadUserSubscriptionsUserSubscriptionsGetResponse,
    ReadUserSubscriptionsUserSubscriptionsGetError,
    ThrowOnError
  >({
    ...options,
    url: '/user/subscriptions',
  });
};

/**
 * Read User Collections
 */
export const readUserCollectionsUserCollectionsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<ReadUserCollectionsUserCollectionsGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ReadUserCollectionsUserCollectionsGetResponse,
    ReadUserCollectionsUserCollectionsGetError,
    ThrowOnError
  >({
    ...options,
    url: '/user/collections',
  });
};

/**
 * Read User Cards
 */
export const readUserCardsUserCardsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadUserCardsUserCardsGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ReadUserCardsUserCardsGetResponse,
    ReadUserCardsUserCardsGetError,
    ThrowOnError
  >({
    ...options,
    url: '/user/cards',
  });
};

/**
 * Read User Files
 */
export const readUserFilesUserFilesGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadUserFilesUserFilesGetData, ThrowOnError>
) => {
  return (options?.client ?? client).get<
    ReadUserFilesUserFilesGetResponse,
    ReadUserFilesUserFilesGetError,
    ThrowOnError
  >({
    ...options,
    url: '/user/files',
  });
};

/**
 * Create User
 */
export const createUserUserRegisterPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateUserUserRegisterPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    CreateUserUserRegisterPostResponse,
    CreateUserUserRegisterPostError,
    ThrowOnError
  >({
    ...options,
    url: '/user/register',
  });
};

/**
 * Update User
 */
export const updateUserUserEditProfilePut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateUserUserEditProfilePutData, ThrowOnError>
) => {
  return (options?.client ?? client).put<
    UpdateUserUserEditProfilePutResponse,
    UpdateUserUserEditProfilePutError,
    ThrowOnError
  >({
    ...options,
    url: '/user/edit_profile',
  });
};

/**
 * Delete User
 */
export const deleteUserUserDeleteProfileDelete = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).delete<
    DeleteUserUserDeleteProfileDeleteResponse,
    DeleteUserUserDeleteProfileDeleteError,
    ThrowOnError
  >({
    ...options,
    url: '/user/delete_profile',
  });
};

/**
 * Authenticate User
 */
export const authenticateUserUserLoginPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<AuthenticateUserUserLoginPostData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    AuthenticateUserUserLoginPostResponse,
    AuthenticateUserUserLoginPostError,
    ThrowOnError
  >({
    ...options,
    url: '/user/login',
  });
};

/**
 * Logout User
 */
export const logoutUserUserLogoutPost = <ThrowOnError extends boolean = false>(
  options?: Options<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    LogoutUserUserLogoutPostResponse,
    LogoutUserUserLogoutPostError,
    ThrowOnError
  >({
    ...options,
    url: '/user/logout',
  });
};
